name: Build manylinux wheel
on:
  push:
  pull_request:


jobs:
  build:
    steps:
      - uses: actions/checkout@v6
      - run: ./ci/docker-build.bash
      - uses: actions/upload-artifact@v4
        path: wheelhouse/*
