name: cibuildwheel for windows

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
#        os: [ubuntu-latest, windows-latest, macos-14]
    env:
      CIBW_BUILD: "cp313-macosx_arm64"

    steps:

      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.3.1

      - name: windows-config
        if: startsWith(matrix.os, 'windows')
        run: |
          echo SKBUILD_CMAKE_ARGS="-G Ninja;-DCMAKE_Fortran_COMPILER=c:/mingw64/bin/gfortran.exe;-DCMAKE_C_COMPILER=c:/mingw64/bin/gcc.exe" >> $env:GITHUB_ENV

      - name: macos-config
        if: startsWith(matrix.os, 'macos')
        run: |
          echo SKBUILD_CMAKE_ARGS="-DCMAKE_Fortran_COMPILER=$(command -v gfortran-15)" >> $env:GITHUB_ENV

      - name: Build wheels
        run:  python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v6
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
